### ISSUE TITLE
Back-end things!

### ISSUE THREAD

**Issue by brunoocasali** [Unisep/truco-marker#1]
# TODO:
- [ ] Criar um evento onde seja possível incrementar a quantidade de partidas ganhas por "nós" ou "eles".
- [ ] Criar o evento que possibilite voltar jogadas.
- [x] Arrumar o problema da lista, (que não exibe os marcadores de jogadas).
- [x] Criar o evento de cancelar partidas!
- [x] Criar o evento de iniciar partidas!
